### ISSUE TITLE
Open to a react app based on your data?

### ISSUE THREAD

**Issue by chmac** [TripSit/combogen#10]
I've whipped up a simple single page app (from create-react-app) which uses your data and allows a user to select multiple drugs, then see the combinations of those drugs. Y'all open to hosting such a thing? I'd be happy to MIT license it. Otherwise I was gonna put it on a subdomain of drugsluts.com just because, hey, why not! :-)

**Comment by chmac** [comment]
It's now up https://combos.drugsluts.com/

**Comment by debuos512** [comment]
This is super cool! Nice work. We've been thinking about doing something like this for a while. I think we'd definitely like to host it - the 'poster' interface doesn't work so nicely when you're looking things up on a screen!

**Comment by chmac** [comment]
@reality Awesome. It's a pretty simple create-react-app setup. I just cloned (stole) your config.json and data files. I put them into the repo out of sheer laziness.

Currently the repo is private, but no need for that, I can easily make it public. Then what? Transfer it to the @TripSit organisation? Y'all setup to handle the build / etc process? I'm happy to add an MIT license to the code. Should probably do that before I transfer the repo.

**Comment by debuos512** [comment]
Hi, we can handle the build/hosting etc. Transferring it to the TripSit org sounds good, or we could just fork your repo to the org (I'm not sure how actual 'transfers' work on GitHub). Let us know when you've made the changes you need to re licensing etc, then we'll get it set up soon :-)

**Comment by chmac** [comment]
@reality I've finally added a license and made the repo public:
https://github.com/chmac/comboapp

I tried to transfer it to @TripSit but I get:

> You don’t have the permission to create repositories on TripSit

I guess I could transfer it to you, then you to the org, or you can give me permission to create repos for the org. Up to you which is easier.

**Comment by chmac** [comment]
@reality What's the word?

**Comment by Spacebjorn** [comment]
I am working on adapting it for our site. We were going to release it with some other stuff but ran into delays and summer.

**Comment by Spacebjorn** [comment]
live here: https://combo.tripsit.me/index.html

**Comment by chmac** [comment]
Awesome, looks great. Looks like you're building it from a fork rather than transferring the original repo. Wanna open up issues on that repo? Right now there's no option to post issues.

https://github.com/TripSit/comboapp

I was going to put the substances into alphabetical order. They're currently ordered in groups. I think that approach makes sense on the chart but not so much on the app. I'm happy to whip up a PR if y'all are open to the idea.

**Comment by Spacebjorn** [comment]
It's been opened up to issues now. 
the sorting sounds good to me. Do you perchance have a link that explains some of the (props: Props) ting = props type code? I'm not very familiar with Redux nor really React tbf, but the redux part stumbles me :)

**Comment by chmac** [comment]
@Spacebjorn That `: Props` syntax is from flow - https://flow.org

It gets stripped out as part of the build process. Essentially it's static typing for javascript.

The redux stuff is a little more involved to get started with. Unless there's a compelling reason to, it probably doesn't need much by way of changes. The redux docs are great btw, but trying to start out by reading the code definitely didn't work for me. If you're getting into react I highly recommend putting a few hours into learning redux, it's been game changing in my react adventures.
